### ISSUE TITLE
Cannot add entries (no error shown in UI)

### ISSUE THREAD

**Issue by leplatrem** [peterbe/workon#4]
I enter some text, press enter, and nothing happens.

In the console I can see:
- the known error `"getLastModified() The operation failed for reasons unrelated to the database itself and not covered by any other error code."`
- `Unhandled promise rejection DOMException: "The operation failed for reasons unrelated to the database itself and not covered by any other error code."`

![screenshot from 2018-09-14 15-28-11](https://user-images.githubusercontent.com/546692/45553038-fdc19d00-b832-11e8-83d7-18a6e5354d74.png)

**Comment by peterbe** [comment]
I get those errors in the console too. But I can definitely add. And things get sent to Kinto successfully. 

What does this output in your web console? 
```
>> localStorage.hideDone
```

**Comment by leplatrem** [comment]
I could not reproduce the DOMException issue from a fresh profile, so I guess it was more a profile/Firefox issue. Closing :|
